### ISSUE TITLE
Red-browed Treecreeper  (Climacteris erythrops) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#11]
**Workflow details**

Common name: Red-browed Treecreeper 
Scientific name: Climacteris erythrops
Group: Birds
Region: ACT NSW Qld Vic
Analyst:
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Ready to review @Doi90

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
