### ISSUE TITLE
Gang-gang Cockatoo (Callocephalon fimbriatum) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#113]
**Workflow details**

Common name: Gang-gang Cockatoo
Scientific name: Callocephalon fimbriatum
Group: Birds
Region: SA Vic NSW ACT
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting on this

**Comment by assma1** [comment]
@AugustHao was this OK without RBG?

**Comment by AugustHao** [comment]
@assma1 I think it looks ok except for the mid-range values on western coastal SA predictions

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
