### ISSUE TITLE
South-eastern Glossy Black-Cockatoo (Calyptorhynchus lathami lathami) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#114]
**Workflow details**

Common name: South-eastern Glossy Black-Cockatoo
Scientific name: Calyptorhynchus lathami lathami
Group: Birds
Region: Vic NSW ACT Qld
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting on this now.

**Comment by assma1** [comment]
Pause workflow for now. Prediction and presence points not close to match.

**Comment by assma1** [comment]
Re-running with RB now.

**Comment by assma1** [comment]
Run with random background. Output looks OK, may be issues with synonyms. Ready for review @rvalavi

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
