### ISSUE TITLE
Kangaroo Island Western Whipbird (Psophodes nigrogularis lashmari) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#115]
**Workflow details**

Common name: Kangaroo Island Western Whipbird
Scientific name: Psophodes nigrogularis lashmari
Group: Birds
Region: SA
Analyst:
Reviewer (code): Adam Smart @assma1  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting now.

**Comment by assma1** [comment]
No data available for species.

**Comment by AugustHao** [comment]
redoing this with new KI data

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
