### ISSUE TITLE
Kangaroo Island Southern Emu-wren (Stipiturus malachurus halmaturinus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#116]
**Workflow details**

Common name: Kangaroo Island Southern Emu-wren
Scientific name: Stipiturus malachurus halmaturinus
Group: Birds
Region: SA
Analyst: Adam
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting now.

**Comment by assma1** [comment]
Re-doing with KI data now.

**Comment by assma1** [comment]
Ready for review @dsouthwell

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
