### ISSUE TITLE
Mainland Dusky Antechinus (Antechinus mimetes) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#117]
**Workflow details**

Common name: Mainland Dusky Antechinus
Scientific name: Antechinus mimetes
Group: Mammals
Region: Vic NSW ACT
Analyst: Adam
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting now.

**Comment by Doi90** [comment]
Done in #178

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
