### ISSUE TITLE
Oakview Leaf-tailed Gecko (Phyllurus kabikabi) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#118]
**Workflow details**

Common name: Oakview Leaf-tailed Gecko
Scientific name: Phyllurus kabikabi
Group: Reptiles
Region: Qld
Analyst:
Reviewer (code): David Wilkinson @Doi90  
Reviewer (output):

**Progress**

- [x] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Not enough presence records via first check. Ready for review @Doi90

**Comment by assma1** [comment]
Re-run. Not enough presence records (n = 1). Ready for review @Doi90

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
