### ISSUE TITLE
Kate's Leaf-tail Gecko (Saltuarius kateae) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#119]
**Workflow details**

Common name: Kate's Leaf-tail Gecko
Scientific name: Saltuarius kateae
Group: Reptiles
Region: NSW
Analyst: Adam
Reviewer (code): David Wilkinson @Doi90  
Reviewer (output):

**Progress**

- [x] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Restarting here

**Comment by assma1** [comment]
Ready for review n = 3 points passed check.

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
