### ISSUE TITLE
Hastings River Mouse, Koontoo (Pseudomys oralis) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#12]
**Workflow details**

Common name: Hastings River Mouse, Koontoo
Scientific name: Pseudomys oralis
Group: Mammals
Region: NSW Qld
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting this

**Comment by assma1** [comment]
Re-running this with RBG now. Taking over from @AugustHao

**Comment by assma1** [comment]
Workflow complete. Ran with RBG. Output OK, some minor errors predicting near Townsville. Ready for review @AugustHao

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
