### ISSUE TITLE
Long-footed Potoroo (Potorous longipes) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#13]
**Workflow details**

Common name: Long-footed Potoroo
Scientific name: Potorous longipes
Group: Mammals
Region: NSW Vic
Analyst:
Reviewer (code): Adam Smart @assma1 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Ready to review @assma1

**Comment by AugustHao** [comment]
redoing this with random

**Comment by AugustHao** [comment]
rerunning this with random background

**Comment by AugustHao** [comment]
done @assma1

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
