### ISSUE TITLE
Mountain Pygmy-possum (Burramys parvus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#14]
**Workflow details**

Common name: Mountain Pygmy-possum
Scientific name: Burramys parvus
Group: Mammals
Region: NSW Vic
Analyst: August
Reviewer (code): David Wilkinson @Doi90
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting on this

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
