### ISSUE TITLE
Broad-toothed Rat (mainland), Tooarrana (Mastacomys fuscus mordicus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#15]
**Workflow details**

Common name: Broad-toothed Rat (mainland), Tooarrana
Scientific name: Mastacomys fuscus mordicus
Group: Mammals
Region: ACT NSW Vic
Analyst:
Reviewer (code): August Hao @AugustHao 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Ready to review! @AugustHao

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
