### ISSUE TITLE
Smoky Mouse, Konoom (Pseudomys fumeus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#16]
**Workflow details**

Common name: Smoky Mouse, Konoom
Scientific name: Pseudomys fumeus
Group: Mammals
Region: ACT NSW Vic
Analyst: Adam
Reviewer (code): Darren Southwell @dsouthwell
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by Doi90** [comment]
Starting this one

**Comment by Doi90** [comment]
My computer can't hack the prediction computation so I'm leaving this one. The data, model, and model_eval objects are synced to Dropbox, whoever takes over just needs to load them in and do the prediction step.

**Comment by AugustHao** [comment]
continuing this one

**Comment by AugustHao** [comment]
still can't do predictions, maybe @rvalavi can have a go?

**Comment by assma1** [comment]
Re-doing this one now @Doi90 @AugustHao

**Comment by assma1** [comment]
Output looks spot on. Ready for review @dsouthwell

**Comment by Doi90** [comment]
@dsouthwell has enough on at the moment so I reviewed it. Looks good!

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
