### ISSUE TITLE
Tyler's Toadlet (Uperoleia tyleri) workflow

### ISSUE THREAD

**Issue by AugustHao** [Doi90/bushfireSOS_workflow#160]
**Workflow details**

Common name: Tyler's Toadlet
Scientific name :Uperoleia tyleri
Group: Frogs
Region: NSW, VIC
Analyst: @AugustHao 
Reviewer (code): 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting on this

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
