### ISSUE TITLE
Parma Wallaby (Notomacropus parma) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#18]
**Workflow details**

Common name: Parma Wallaby
Scientific name: Notomacropus parma
Group: Mammals
Region: NSW Qld
Analyst:
Reviewer (code): August Hao @AugustHao 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
try Notamacropus parma

**Comment by rvalavi** [comment]
The prediction map is suspicious!

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
