### ISSUE TITLE
Yellow-bellied Glider (Petaurus australis) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#19]
**Workflow details**

Common name: Yellow-bellied Glider
Scientific name: Petaurus australis
Group: Mammals
Region: NSW Qld SA Vic
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
starting this one

**Comment by assma1** [comment]
Taking over from @dsouthwell.

**Comment by assma1** [comment]
Ready for review @rvalavi  Output looks good.

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
