### ISSUE TITLE
Rufous Scrub-bird (Atrichornis rufescens) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#2]
**Workflow details**

Common name: Rufous Scrub-bird
Scientific name: Atrichornis rufescens
Group: Birds
Region: NSW Qld
Analyst:
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
@rvalavi what is the status of this species? Should I re-run with RB?

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
