### ISSUE TITLE
Greater Glider (Petauroides volans) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#20]
**Workflow details**

Common name: Greater Glider
Scientific name: Petauroides volans
Group: Mammals
Region: ACT NSW Qld Vic
Analyst:
Reviewer (code): Darren Southwell @dsouthwell
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting now.

**Comment by assma1** [comment]
Ready for review @dsouthwell

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
