### ISSUE TITLE
Brush-tailed Rock-wallaby (Petrogale penicillata) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#21]
**Workflow details**

Common name: Brush-tailed Rock-wallaby
Scientific name: Petrogale penicillata
Group: Mammals
Region: NSW Qld Vic
Analyst: Roozbeh
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Ready to review! @Doi90

**Comment by assma1** [comment]
Opening again to re-run with random background points.

**Comment by rvalavi** [comment]
re-ran this with random BG @Doi90

**Comment by Doi90** [comment]
The pull request for this one was merged in @rvalavi, so you'll need to create a new one for your random BG script.

**Comment by assma1** [comment]
Think we have doubled on this perhaps @rvalavi

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
