### ISSUE TITLE
Long-nosed Potoroo (SE Mainland) (Potorous tridactylus tridactylus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#22]
**Workflow details**

Common name: Long-nosed Potoroo (SE Mainland)
Scientific name: Potorous tridactylus tridactylus
Group: Mammals
Region: NSW Qld SA Vic
Analyst:
Reviewer (code): Adam Smart @assma1 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
rerunning with random bg

**Comment by Doi90** [comment]
Added a commit to the branch with the other subspecies names added to the script to grab the VIC data. Can you rerun it @AugustHao ?

**Comment by AugustHao** [comment]
rerunning now

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
