### ISSUE TITLE
Spot-tailed Quoll, Spotted-tail Quoll, Tiger Quoll (Dasyurus maculatus maculatus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#23]
**Workflow details**

Common name: Spot-tailed Quoll, Spotted-tail Quoll, Tiger Quoll
Scientific name: Dasyurus maculatus maculatus (South-east mainland population)
Group: Mammals
Region: ACT NSW Qld Vic
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
starting this one

**Comment by assma1** [comment]
Any updates on this @dsouthwell?

**Comment by dsouthwell** [comment]
I haven’t revisited it. Feel free to run it again….have been tied up with Zonation all day

**Comment by assma1** [comment]
Taking over from @dsouthwell. Re-running with RB now.

**Comment by assma1** [comment]
Re-ran. Output looks good - ready for review @rvalavi

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
