### ISSUE TITLE
New Holland Mouse, Pookila (Pseudomys novaehollandiae) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#24]
**Workflow details**

Common name: New Holland Mouse, Pookila
Scientific name: Pseudomys novaehollandiae
Group: Mammals
Region: NSW Qld Tas Vic
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting on this

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
