### ISSUE TITLE
Grey-headed Flying-fox (Pteropus poliocephalus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#25]
**Workflow details**

Common name: Grey-headed Flying-fox
Scientific name: Pteropus poliocephalus
Group: Mammals
Region: VIC, NSW, QLD, SA, ACT, WA, TAS
Analyst: Roozbeh
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Ready to review @Doi90

**Comment by assma1** [comment]
Re-opening this one for remodelling with random background.

**Comment by assma1** [comment]
Ready for (re)review @Doi90 @dsouthwell

**Comment by Doi90** [comment]
Have you pushed up the new changes @assma1? The pull request is just showing @rvalavi's TGB version and no commits from you.

**Comment by assma1** [comment]
I thought I had - will double check now. I certainly ran it!

**Comment by assma1** [comment]
Sorry had not pushed. OK now @Doi90

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
