### ISSUE TITLE
Golden-tipped Bat (Phoniscus papuensis) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#26]
**Workflow details**

Common name: Golden-tipped Bat
Scientific name: Phoniscus papuensis
Group: Mammals
Region: NSW
Analyst:
Reviewer (code): August Hao @AugustHao 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by Doi90** [comment]
Merged in the pull request for Litoria spenceri #157

**Comment by AugustHao** [comment]
redoing this

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
