### ISSUE TITLE
Platypus (Ornithorhynchus anatinus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#27]
**Workflow details**

Common name: Platypus
Scientific name: Ornithorhynchus anatinus
Group: Mammals
Region: ACT NSW Qld SA Tas Vic
Analyst:
Reviewer (code): Darren Southwell @dsouthwell
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
starting this one even though im a reviewer

**Comment by dsouthwell** [comment]
did this one even though Im a reviewer. sent to adam to review

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
