### ISSUE TITLE
Blue Mountains Water Skink (Eulamprus leuraensis) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#28]
**Workflow details**

Common name: Blue Mountains Water Skink
Scientific name: Eulamprus leuraensis
Group: Reptiles
Region: NSW
Analyst:
Reviewer (code): August Hao @AugustHao 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by Doi90** [comment]
Starting this one

**Comment by Doi90** [comment]
Ready for review @AugustHao

**Comment by AugustHao** [comment]
species known to be endemic to blue mountains but prediction included Kosciuszko, might need to crop prediction layer for Zonation @dsouthwell

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
