### ISSUE TITLE
Regent Honeyeater (Anthochaera phrygia) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#3]
**Workflow details**

Common name: Regent Honeyeater
Scientific name: Anthochaera phrygia
Group: Birds
Region: ACT NSW Qld SA Vic 
Analyst:
Reviewer (code): August Hao @AugustHao 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting on this one now.

**Comment by assma1** [comment]
Re-ran with RBG. Ready for review @AugustHao

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
