### ISSUE TITLE
Bell's Turtle (Wollumbinia belli) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#31]
**Workflow details**

Common name: Bell's Turtle
Scientific name: Wollumbinia belli
Group: Reptiles
Region: NSW Qld
Analyst:
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting on this one

**Comment by Doi90** [comment]
PB workflow complete

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
