### ISSUE TITLE
Broad-headed Snake (Hoplocephalus bungaroides) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#33]
**Workflow details**

Common name: Broad-headed Snake
Scientific name: Hoplocephalus bungaroides
Group: Reptiles
Region: NSW
Analyst: Darren
Reviewer (code): David Wilkinson @Doi90  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
Making a start on this one

**Comment by dsouthwell** [comment]
starting this one again

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
