### ISSUE TITLE
Kaputar Rock Skink (Egernia roomi) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#34]
**Workflow details**

Common name: Kaputar Rock Skink
Scientific name: Egernia roomi
Group: Reptiles
Region: NSW
Analyst:
Reviewer (code): Darren Southwell @dsouthwell
Reviewer (output):

**Progress**

- [ ] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
No data are available @dsouthwell

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
