### ISSUE TITLE
Guthega Skink (Liopholis guthega) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#35]
**Workflow details**

Common name: Guthega Skink
Scientific name: Liopholis guthega
Group: Reptiles
Region: NSW Vic
Analyst:
Reviewer (code): Darren Southwell @dsouthwell
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Ready for review @dsouthwell

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
