### ISSUE TITLE
Alpine She-oak Skink (Cyclodomorphus praealtus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#36]
**Workflow details**

Common name: Alpine She-oak Skink
Scientific name: Cyclodomorphus praealtus
Group: Reptiles
Region: NSW Vic
Analyst:
Reviewer (code): August Hao @AugustHao 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Not enough points! @AugustHao

**Comment by AugustHao** [comment]
@rvalavi  can you push your script and comment how many data points you got?

**Comment by rvalavi** [comment]
@AugustHao done!

**Comment by rvalavi** [comment]
Fitted again! There was no data at the beginning! @AugustHao

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
