### ISSUE TITLE
Three-toed Snake-tooth Skink (Coeranoscincus reticulatus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#37]
**Workflow details**

Common name: Three-toed Snake-tooth Skink
Scientific name: Coeranoscincus reticulatus
Group: Reptiles
Region: NSW Qld
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [x] Output reviewed by Reviewer (output)
- [x] Workflow complete

**Comment by AugustHao** [comment]
starting on this one

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
