### ISSUE TITLE
Southern Water-skink (Eulamprus tympanum) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#38]
**Workflow details**

Common name: Southern Water-skink
Scientific name: Eulamprus tympanum
Group: Reptiles
Region: NSW SA Vic
Analyst:
Reviewer (code): Adam Amart @assma1  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Done! ready to review! @assma1

**Comment by rvalavi** [comment]
New run! You can review now @assma1

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
