### ISSUE TITLE
Glossy Grass Skink (Pseudemoia rawlinsoni) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#39]
**Workflow details**

Common name: Glossy Grass Skink
Scientific name: Pseudemoia rawlinsoni
Group: Reptiles
Region: ACT NSW SA Tas Vic
Analyst:
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
@Doi90  This is done!

**Comment by rvalavi** [comment]
Done! good to review @Doi90

**Comment by Doi90** [comment]
I don't see a pull request for it @rvalavi ?

**Comment by rvalavi** [comment]
I fitted the model and it has the prediction! Where can be the problem? @Doi90

**Comment by Doi90** [comment]
![image](https://user-images.githubusercontent.com/13193240/86314637-83fadd80-bc6b-11ea-8d8a-87440b491f7d.png)

Those are the only pull requests visible from you. Did you create a pull request for this species or did you just push up the branch?

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
