### ISSUE TITLE
Eastern Bristlebird (Dasyornis brachypterus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#4]
**Workflow details**

Common name: Eastern Bristlebird
Scientific name: Dasyornis brachypterus
Group: Birds
Region: NSW Qld Vic
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
starting this one

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
