### ISSUE TITLE
Moritz's Leaf-tailed Gecko (Saltuarius moritzi) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#41]
**Workflow details**

Common name: Moritz's Leaf-tailed Gecko
Scientific name: Saltuarius moritzi
Group: Reptiles
Region: NSW
Analyst:
Reviewer (code): @assma1  
Reviewer (output):

**Progress**

- [ ] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Revisiting

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
