### ISSUE TITLE
Mustard-bellied Snake (Drysdalia rhodogaster) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#42]
**Workflow details**

Common name: Mustard-bellied Snake
Scientific name: Drysdalia rhodogaster
Group: Reptiles
Region: NSW
Analyst: Darren
Reviewer (code): Roozbeh Valavi @rvalavi  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
Started by Darren Southwell

**Comment by dsouthwell** [comment]
Everything works except the Boyce Index returned NA

**Comment by dsouthwell** [comment]
Have re-run using updated functions - everything seems to work

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
