### ISSUE TITLE
Red-tailed Calyptotis (Calyptotis ruficauda) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#43]
**Workflow details**

Common name: Red-tailed Calyptotis
Scientific name: Calyptotis ruficauda
Group: Reptiles
Region: NSW
Analyst:
Reviewer (code): Adam Smart @assma1  
Reviewer (output):

**Progress**

- [ ] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
All done, ready to review @assma1

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
