### ISSUE TITLE
Granite Leaf-tailed Gecko (Saltaurius wyberba) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#44]
**Workflow details**

Common name: Granite Leaf-tailed Gecko
Scientific name: Saltaurius wyberba
Group: Reptiles
Region: NSW Qld
Analyst:
Reviewer (code): Darren Southwell @dsouthwell
Reviewer (output):

**Progress**

- [ ] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Done! there was no data @dsouthwell

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
