### ISSUE TITLE
Broad-tailed Gecko (Phyllurus platurus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#45]
**Workflow details**

Common name: Broad-tailed Gecko
Scientific name: Phyllurus platurus
Group: Reptiles
Region: NSW
Analyst: Roozbeh
Reviewer (code): David Wilkinson @Doi90
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
@dsouthwell done!

**Comment by rvalavi** [comment]
Done! ready for review @dsouthwell

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
