### ISSUE TITLE
Pugh's Frog (Philoria pughi) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#48]
**Workflow details**

Common name: Pugh's Frog
Scientific name: Philoria pughi
Group: Frogs
Region: NSW
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
My bad! I'm the reviewer!!

**Comment by AugustHao** [comment]
starting on this one

**Comment by AugustHao** [comment]
workflow complete using predlayer masked for native veg only - may need revisit in the future with updated pred stack but I doubt it makes a difference - species appears to be native restricted

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
