### ISSUE TITLE
Sphagnum Frog (Philoria sphagnicola) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#49]
**Workflow details**

Common name: Sphagnum Frog
Scientific name: Philoria sphagnicola
Group: Frogs
Region: NSW
Analyst:
Reviewer (code): David Wilkinson @Doi90  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting here.

**Comment by assma1** [comment]
Model fitted. Output looks OK.

**Comment by AugustHao** [comment]
we need to revisit this one - I pulled down more NSW data that were under a synonym @assma1 

The data is uploaded in Dropbox, so just need to rerun the data getting function

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
