### ISSUE TITLE
Albert's Lyrebird (Menura alberti) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#5]
**Workflow details**

Common name: Albert's Lyrebird
Scientific name: Menura alberti
Group: Birds
Region: NSW Qld
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
starting this one

**Comment by dsouthwell** [comment]
very range restricted species - predicts outside of range into northern QLD. Might have to revisit with spatial term

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
