### ISSUE TITLE
Peppered Tree Frog (Litoria piperata) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#50]
**Workflow details**

Common name: Peppered Tree Frog
Scientific name: Litoria piperata
Group: Frogs
Region: NSW
Analyst:
Reviewer (code): August Hao @AugustHao  
Reviewer (output):

**Progress**

- [ ] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
@rvalavi  please push your script with comments on the number of presences you found

**Comment by rvalavi** [comment]
This is updated and with the number of points (6 points) @AugustHao

**Comment by rvalavi** [comment]
New run with the change in the location of the data folder. But still not enough data @AugustHao

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
