### ISSUE TITLE
Southern Corroboree Frog (Pseudophryne corroboree) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#51]
**Workflow details**

Common name: Southern Corroboree Frog
Scientific name: Pseudophryne corroboree
Group: Frogs
Region: NSW
Analyst:
Reviewer (code): August Hao @AugustHao  
Reviewer (output):

**Progress**

- [x] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
@AugustHao done, not enough records!

**Comment by rvalavi** [comment]
Done! ready to review! @AugustHao

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
