### ISSUE TITLE
Spotted Tree Frog (Litoria spenceri) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#52]
**Workflow details**

Common name: Spotted Tree Frog
Scientific name: Litoria spenceri
Group: Frogs
Region: NSW Vic
Analyst: Darren
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
starting this one

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
