### ISSUE TITLE
Giant Burrowing Frog (Heleioporus australiacus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#53]
**Workflow details**

Common name: Giant Burrowing Frog
Scientific name: Heleioporus australiacus
Group: Frogs
Region: NSW Vic
Analyst:
Reviewer (code): Adam Smart @assma1 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
Starting this one

**Comment by dsouthwell** [comment]
No data from Vic, but think there should be. Need to check .

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
