### ISSUE TITLE
New England treefrog, Glandular Frog (Litoria subglandulosa) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#54]
**Workflow details**

Common name: New England treefrog, Glandular Frog
Scientific name: Litoria subglandulosa
Group: Frogs
Region: NSW Qld
Analyst: Roozbeh
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
@dsouthwell no records!

**Comment by rvalavi** [comment]
Ready to review  @dsouthwell

**Comment by rvalavi** [comment]
Re-ran; ready for review @dsouthwell

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
