### ISSUE TITLE
Littlejohn's Tree Frog, Heath Frog (Litoria littlejohni) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#55]
**Workflow details**

Common name: Littlejohn's Tree Frog, Heath Frog
Scientific name: Litoria littlejohni
Group: Frogs
Region: NSW Vic
Analyst: Roozbeh
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
I'm starting this one!

**Comment by rvalavi** [comment]
@dsouthwell ready for review!

**Comment by rvalavi** [comment]
Done! ready to review @dsouthwell

**Comment by Doi90** [comment]
Merged in #132

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
