### ISSUE TITLE
Davies' Tree Frog (Litoria daviesae) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#57]
**Workflow details**

Common name: Davies' Tree Frog
Scientific name: Litoria daviesae
Group: Frogs
Region: NSW
Analyst:
Reviewer (code): August Hao @AugustHao  
Reviewer (output):

**Progress**

- [x] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Less than 20 species records (n = 10). Ready for code review @AugustHao

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
