### ISSUE TITLE
Stuttering Frog, Southern Barred Frog  (Mixophyes balbus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#58]
**Workflow details**

Common name: Stuttering Frog, Southern Barred Frog 
Scientific name: Mixophyes balbus
Group: Frogs
Region: NSW
Analyst: Darren
Reviewer (code): David Wilkinson @Doi90 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by dsouthwell** [comment]
Darren starting this one

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
