### ISSUE TITLE
Giant Barred Frog (Mixophyes iteratus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#59]
**Workflow details**

Common name: Giant Barred Frog
Scientific name: Mixophyes iteratus
Group: Frogs
Region: NSW Qld
Analyst:
Reviewer (code): Darren Southwell @dsouthwell
Reviewer (output):

**Progress**

- [x] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
No enough species records n = 0

**Comment by assma1** [comment]
Re-visiting now.

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
