### ISSUE TITLE
Mainland Ground Parrot (Pezoporus wallicus wallicus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#6]
**Workflow details**

Common name: Mainland Ground Parrot
Scientific name: Pezoporus wallicus wallicus
Group: Birds
Region: NSW Qld Vic
Analyst:
Reviewer (code): Adam Smart @assma1 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
Ready to review! @assma1

**Comment by rvalavi** [comment]
I re-ran it with VIC! @assma1

**Comment by Doi90** [comment]
I pushed up a commit with a new workflow script @rvalavi, can you run it again? My computer can't hack it on birds. The new script accounts for the different species name in the VIC database.

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
