### ISSUE TITLE
Fleay's Frog (Mixophyes fleayi) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#60]
**Workflow details**

Common name: Fleay's Frog
Scientific name: Mixophyes fleayi
Group: Frogs
Region: NSW Qld
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting on this one

**Comment by AugustHao** [comment]
ran with native-only masked predlayers - should not be an issue for a native-restricted species, but flagged for possible revisit

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
