### ISSUE TITLE
Western Ground Parrot (Pezoporus wallicus flaviventris) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#88]
**Workflow details**

Common name: Western Ground Parrot
Scientific name: Pezoporus wallicus flaviventris
Group: Birds
Region: WA
Analyst:
Reviewer (code): Roozbeh Valavi @rvalavi  
Reviewer (output):

**Progress**

- [x] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting this.

**Comment by assma1** [comment]
Ready for review @rvalavi. Only four presence records found. Species name used was Pezoporus flaviventris NOT Pezoporus wallicus flaviventris (0 records returned).

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
