### ISSUE TITLE
Kangaroo Island Glossy Black-Cockatoo (Calyptorhynchus lathami halmaturinus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#89]
**Workflow details**

Common name: Kangaroo Island Glossy Black-Cockatoo
Scientific name: Calyptorhynchus lathami halmaturinus
Group: Birds
Region: SA
Analyst: August
Reviewer (code): David Wilkinson @Doi90  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
on this

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
