### ISSUE TITLE
Pilotbird (Pycnoptilus floccosus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#9]
**Workflow details**

Common name: Pilotbird
Scientific name: Pycnoptilus floccosus
Group: Birds
Region: ACT NSW Vic
Analyst:
Reviewer (code): Adam Smarth @assma1 
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting on this

**Comment by assma1** [comment]
Re-running with RB @AugustHao

**Comment by assma1** [comment]
Ready for review @dsouthwell  @AugustHao . Output looks good!

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
