### ISSUE TITLE
Bassian Thrush, Western Bassian Thrush (Zoothera lunulata halmaturina) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#90]
**Workflow details**

Common name: Bassian Thrush (South Australian), Western Bassian Thrush
Scientific name: Zoothera lunulata halmaturina
Group: Birds
Region: SA
Analyst: August
Reviewer (code): Adam Smart @assma1  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting this

**Comment by AugustHao** [comment]
redoing this now

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
