### ISSUE TITLE
Kangaroo Island Dunnart (Sminthopsis griseoventer aitkeni) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#91]
**Workflow details**

Common name: Kangaroo Island Dunnart
Scientific name: Sminthopsis griseoventer aitkeni
Group: Mammals
Region: SA
Analyst:
Reviewer (code): August Hao @AugustHao  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by rvalavi** [comment]
The correct name is: Sminthopsis fuliginosus aitkeni

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
