### ISSUE TITLE
Kangaroo Island Echidna (Tachyglossus aculeatus multiaculeatus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#92]
**Workflow details**

Common name: Kangaroo Island Echidna
Scientific name: Tachyglossus aculeatus multiaculeatus
Group: Mammals
Region: SA
Analyst:
Reviewer (code): August Hao @AugustHao  
Reviewer (output):

**Progress**

- [x] Obtained data
- [x] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [x] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by assma1** [comment]
Starting on this now.

**Comment by assma1** [comment]
Workflow complete. Output OK, ready for review.

**Comment by rvalavi** [comment]
Has been re-run @AugustHao

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
