### ISSUE TITLE
Silver-headed Antechinus (Antechinus argentus) workflow

### ISSUE THREAD

**Issue by Doi90** [Doi90/bushfireSOS_workflow#93]
**Workflow details**

Common name: Silver-headed Antechinus
Scientific name: Antechinus argentus
Group: Mammals
Region: Qld
Analyst: August
Reviewer (code): David Wilkinson @Doi90  
Reviewer (output):

**Progress**

- [x] Obtained data
- [ ] Fit presence background model workflow
- [ ] (Optional) Fit presence absence model workflow
- [ ] (Optional) Fit hybrid model workflow
- [ ] Workflow reviewed by Reviewer (code)
- [ ] Output reviewed by Reviewer (output)
- [ ] Workflow complete

**Comment by AugustHao** [comment]
starting on this

**Comment by Doi90** [comment]
Closing workflow issues now that DAWE report is submitted. Can be re-opened if/when we need to re-run.
